name: Lint and Format Check

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: apps/fm-app
        run: uv sync

      - name: Run Ruff
        working-directory: apps/fm-app
        run: uv run ruff check .