apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: amqp
              containerPort: 5672
            - name: http
              containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: apegpt-infra-cfg
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: apegpt-infra-sec
                  key: RABBITMQ_PASS
            - name: RABBITMQ_LOG_LEVEL
              value: "warning"
          envFrom:
            - configMapRef:
                name: apegpt-infra-cfg
          resources:
            limits:
              memory: "512Mi"
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: flow-manager-rq
  namespace: prod  # Ensure this matches the namespace in your connection string
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      name: amqp
      port: 5672
      targetPort: 5672
    - protocol: TCP
      name: http
      port: 15672
      targetPort: 15672
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apegpt-infra-cfg
  namespace: prod
  labels:
    app: rabbitmq
data:
  RABBITMQ_USER: 'default_user_gGuMqsvfQyY0LVh_cTM'
