---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fm-app-pvc
  namespace: prod
spec:
  storageClassName: ebs-sc  # Adjust storage class as needed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust size as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fm-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fm-app
  template:
    metadata:
      labels:
        app: fm-app
    spec:
      imagePullSecrets:
        - name: gcr-sa-key
      containers:
        - name: fm-app
          imagePullPolicy: IfNotPresent
          command: [ "./run.sh" ]
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fm-app-cfg
            - secretRef:
                name: fm-app-sec
          volumeMounts:
            - name: gcp-secret
              mountPath: /app/sa
              readOnly: true
        - name: fm-app-celery
          imagePullPolicy: IfNotPresent
          command: [ "./celery_run.sh" ]
          envFrom:
            - configMapRef:
                name: fm-app-cfg
            - secretRef:
                name: fm-app-sec
          volumeMounts:
            - name: gcp-secret
              mountPath: /app/sa
              readOnly: true
            - name: charts-storage
              mountPath: /app/static/charts
      volumes:
        - name: gcp-secret
          secret:
            secretName: gcp-vertex-sa
        - name: charts-storage
          persistentVolumeClaim:
            claimName: fm-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fm-app-svc
  namespace: prod
spec:
  selector:
    app: fm-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fm-app-cfg
  namespace: prod
  labels:
    app: fm-app
data:
  DATABASE_USER: 'fm_app'
  DATABASE_PORT: '5432'
  DATABASE_DB: 'fm_app'
  # DATABASE_WH_USER: 'wh_ro'
  DATABASE_WH_USER: 'wh_user'
  DATABASE_WH_PORT: '9000'
  DATABASE_WH_PORT_NEW: '9000'
  # DATABASE_WH_PORT_V2: '9000'
  DATABASE_WH_PORT_V2: '9440'
  DATABASE_WH_DB: 'wh'
  DATABASE_WH_DB_NEW: 'new_wh'
  DATABASE_WH_DB_V2: 'ct'
  AUTH0_DOMAIN: 'ape-gpt-dev.us.auth0.com'
  AUTH0_API_AUDIENCE: 'http://ape-gpt-api-dev'
  AUTH0_ISSUER: 'https://ape-gpt-dev.us.auth0.com/'
  AUTH0_ALGORITHMS: 'RS256'
  LOG_LEVEL: 'INFO'
  ROOT_PATH: '/'
  DBMETA: 'http://dbmeta-svc:8080/'
  DBREF: 'http://dbref-svc:8080/'
  # switched off for the time being
  IRL_SLOTS: 'http://irl-slots-svc:8080/'
  GOOGLE_PROJECT_ID: 'bustling-bot-438222-t8'
  # OPEN_AI_LLM_NAME: 'chatgpt-4o-latest'
  # OPENAI_LLM_NAME: 'gpt-4.1-2025-04-14'
  # OPENAI_LLM_NAME: 'gpt-5-2025-08-07'
  OPENAI_LLM_NAME: 'gpt-5-mini-2025-08-07'
  # default
  # GOOGLE_LLM_NAME: "gemini-2.0-flash"
  # not too good
  # GOOGLE_LLM_NAME: "gemini-2.5-pro-preview-03-25"
  GOOGLE_LLM_NAME: "gemini-2.5-pro-preview-05-06"
  # default
  # ANTHROPIC_LLM_NAME: 'claude-3-5-sonnet-20240620'
  ANTHROPIC_LLM_NAME: 'claude-3-7-sonnet-20250219'
  DATABASE_WH_PARAMS: '?max_execution_time=120'
  DEEPSEEK_AI_API_URL: 'https://api.deepseek.com/v1'
  GUEST_AUTH_ISSUER: 'https://apegpt.ai'