apiVersion: v1
kind: PersistentVolume
metadata:
  name: fm-app-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  hostPath:
    path: "/mnt/data"