apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch.yml
    target:
      kind: Deployment
      name: dbmeta-app
  - path: patch-etl.yml
    target:
      kind: Job
      name: dbmeta-etl
  - path: patch-config.yml
    target:
      kind: ConfigMap
      name: dbmeta-cfg
