apiVersion: batch/v1
kind: Job
metadata:
  name: dbmeta-etl
  namespace: prod
spec:
  template:
    metadata:
      labels:
        app: dbmeta-etl
    spec:
      containers:
        - name: dbmeta-etl
          image: '205930631794.dkr.ecr.us-east-1.amazonaws.com/dbmeta:4.3'